---
- name: Stop Swift services
  service: name={{ item }} enabled=no state=stopped
  with_items: swift.service_names
  ignore_errors: yes

- name: Remove Swift packages and dependencies
  shell: pip freeze | xargs pip uninstall -y

- debug: var={{ swift_config }}

- name: Remove all files and directories within Swift drives
  command: rm -rf /mnt/{{ item.name }}/*
  with_items: swift_config.drives
