---
- name: Install pip requirements
  pip: requirements=~/{{rpc_repo_dir}}/requirements.txt

- name: Copy rpc_deploy directory
  command: cp -a ~/{{rpc_repo_dir}}/etc/{{config_prefix}}_deploy /etc/{{config_prefix}}_deploy
           creates=/etc/{{config_prefix}}_deploy

- name: Set environment_md5 fact for template
  stat: path=/etc/{{config_prefix}}_deploy/{{config_prefix}}_environment.yml
  register: environment_version

- name: install rpc user config file
  template: src=rpc_user_config.j2
            dest=/etc/{{config_prefix}}_deploy/{{config_prefix}}_user_config.yml

- name: install user variables file
  template: src=user_variables.j2
            dest=/etc/{{config_prefix}}_deploy/user_variables.yml

- name: Create passphrases file
  file: path=/etc/{{config_prefix}}_deploy/user_secrets.yml
        state=touch
        owner=root
        mode=0644

- name: Generate passphrases
  command: ~/{{rpc_repo_dir}}/scripts/pw-token-gen.py --file /etc/{{config_prefix}}_deploy/user_secrets.yml
