- name: install bonding / bridge dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - ifenslave-2.6
    - bridge-utils

- name: prevent bond0 from loading
  lineinfile: dest=/etc/modules regexp='bonding' line='bonding' state=absent

- name: load kernel bonding
  modprobe: name=bonding state=present

- name: ensure /etc/network/interfaces.d exists
  file: path=/etc/network/interfaces.d state=directory owner=root mode=0655

- name: setup interfaces file
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644

- name: retrieve new ip address
  local_action: script cidr.py {{ mgmt_cidr }} {{ ansible_default_ipv4.address }}
  register: container_cidr_address

- name: setup interface config files
  template: dest=/etc/network/interfaces.d/{{ item }}.cfg owner=root group=root mode=0644
  with_items: networking

- name: restart networking
  service: name=networking state=restarted
  async: 45
  poll: 0

- name: add default route
  command: route add default gw {{ network.gateway }} dev {{ network.mgmt.bridge_name }}

- name: wait for reconnect
  wait_for: delay=10 host={{ inventory_hostname }} port=22
  delegate_to: localhost

- name: flush interfaces
  command: ip a f {{ ansible_default_ipv4.interface }}

- name: cycle previous default interface
  shell: '(ifdown {{ ansible_default_ipv4.interface }}; ifup {{ ansible_default_ipv4.interface }}) &'
