---
- name: Add ssh keys
  tags: rpc
  copy: >
    src={{item}}
    dest=~/.ssh/{{item|basename}}
  with_fileglob:
    - id_*

- name: Delete RPC repo
  tags: rpc
  command:
    rm -rf ~/ansible-lxc-rpc

- name: Clone RPC repo
  tags: rpc
  git: >
    repo=https://github.com/rcbops/ansible-lxc-rpc
    dest=~/ansible-lxc-rpc

- name: Update remotes for PR ref
  tags: rpc
  command: >
    git config --add remote.origin.fetch "+refs/pull/*/head:refs/remotes/origin/pr/*"
    chdir=~/ansible-lxc-rpc

- name: Configure git identity
  tags: rpc
  shell: >
    git config --global user.email "jenkins@propter.net";
    git config --global user.name "Jenkins"
  args:
    chdir: "~/ansible-lxc-rpc"

- name: Fetch origin
  tags: rpc
  command: >
    git fetch origin
    chdir=~/ansible-lxc-rpc

- name: Checkout target branch
  tags: rpc
  command: >
    git checkout {{targetBranch}}
    chdir=~/ansible-lxc-rpc

- name: Merge PR
  tags: rpc
  command: >
    git merge --no-edit origin/pr/{{pullRequestID}}
    chdir=~/ansible-lxc-rpc

- name: Install pip
  tags: rpc
  shell: "curl https://bootstrap.pypa.io/get-pip.py|python"

- name: Install pip requirements
  tags: rpc
  pip: requirements=~/ansible-lxc-rpc/requirements.txt

- name: Copy rpc_deploy directory
  tags: rpc
  command: >
    cp -a ~/ansible-lxc-rpc/etc/rpc_deploy ~/rpc_deploy
    creates=~/rpc_deploy

- name: Set environment_md5 fact for template
  tags: rpc
  stat: >
    path=~/rpc_deploy/rpc_environment.yml
  register: st

- name: Set facts for template
  tags: rpc
  set_fact:
    cluster_hosts: "{{groups[hosts]}}"
    environment_md5: "{{st.stat.md5}}"

- name: Render rpc_user_config template
  tags: rpc
  template: >
    src=rpc_user_config.yml
    dest=~/rpc_deploy/rpc_user_config.yml

- name: Generate passphrases
  tags: rpc
  command: >
    ~/ansible-lxc-rpc/scripts/pw-token-gen.py --file ~/rpc_deploy/user_variables.yml

- name: Set virt_type to kvm
  tags: rpc
  lineinfile: >
    dest=~/rpc_deploy/user_variables.yml
    regexp="^virt_type"
    line="virt_type: kvm"

- name: Copy target.sh to host[0]
  tags: rpc
  copy: >
    src=target.sh
    dest=~/target.sh
    mode=0755

- name: Dump host[0] IP to local file
  tags: rpc
  connection: local
  delegate_to: local
  copy: >
    content={{ansible_ssh_host}}
    dest=~/target.ip
