---
- name: Provision dev cluster
  hosts: "{{hosts}}"
  gather_facts: True
  vars:
    - vars/packages.yml
  roles:
    - lvm
    - packages
    - dev-networking
    - dev-swift

- name: Provision dev cluster
  hosts: "{{hosts}}[0]"
  gather_facts: True
  roles:
    - setup-git
    - dev-setup-rpc
