---
- name: Generate hosts
  tags: hosts
  hosts: local
  connection: local
  gather_facts: false
  tasks:
  - name: Add node
    add_host:
      name: "{{host_prefix}}-node{{item}}"
      groups: hosts
      rax_flavor: performance1-4
      iface:
        name: eth2
        ipv4: 172.16.0.{{item}}/24
        tunnel: 172.16.10.{{item}}/24
    with_sequence: count={{host_count}}
