---
- name: create rpc deploy folder
  file: path="{{ lookup('env', 'USER_HOME') }}/rpc_deploy" 
        state=directory 
        owner="{{ lookup('env', 'USER') }}" 
        mode=0755

- name: install rpc environment file
  template: src=rpc_environment.j2 
            dest={{ lookup('env', 'USER_HOME') }}/rpc_deploy/rpc_environment.yml 
            owner="{{ lookup('env', 'USER') }}" 
            mode=0644

- name: get environment version md5sum
  stat: path=~/rpc_deploy/rpc_environment.yml
  register: environment_version

- name: install rpc user config file
  template: src=rpc_user_config.j2 
            dest={{ lookup('env', 'USER_HOME') }}/rpc_deploy/rpc_user_config.yml 
            owner="{{ lookup('env', 'USER') }}" 
            mode=0644
