---
- name: Stop neutron-linuxbridge-agent
  command: service neutron-linuxbridge-agent stop

- name: Get neutron directory
  shell: ls /opt/ | grep neutron
  register: neutron_dir

- name: Uninstall neutron python dependencies
  pip: requirements=/opt/{{ neutron_dir.stdout }}/requirements.txt state=absent

- name: Uninstall neutron and python-novaclient
  pip: name={{ item }} state=absent
  with_items:
    - neutron
    - python-novaclient

- name: Remove neutron directories
  file: path={{ item }} state=absent
  with_items:
    - /opt/{{ neutron_dir.stdout }}
    - /etc/neutron
    - /var/log/neutron
    - /var/lib/neutron