---

- name: Delete RPC repo
  tags:
    - rpc
    - git
  command:
    rm -rf {{rpc_repo_dir}}

- name: Clone RPC repo
  tags:
    - rpc
    - git
  git: >
    repo=https://github.com/rcbops/ansible-lxc-rpc
    dest={{rpc_repo_dir}}

- name: Configure git identity
  tags:
    - rpc
    - git
  shell: >
    git config --global user.email "jenkins@propter.net";
    git config --global user.name "Jenkins"
  args:
    chdir: "{{rpc_repo_dir}}"

- name: "Install git-review"
  pip:
    name: git-review
  when: TRIGGER == "gerrit"

- name: Get change from gerrit
  tags:
    - rpc
    - git
  shell:
    git-review -d {{GERRIT_CHANGE_NUMBER}}
  args:
    chdir: "{{rpc_repo_dir}}"
  when: TRIGGER == "gerrit"


- name: Add github remote refs
  tags:
    - rpc
    - git
  command: >
    git config --add remote.origin.fetch "+refs/pull/*/head:refs/remotes/origin/pr/*"
    chdir={{rpc_repo_dir}}
  when: TRIGGER == "github"

- name: Fetch origin
  tags:
    - rpc
    - git
  command: >
    git fetch origin
    chdir={{rpc_repo_dir}}
  when: TRIGGER == "github"

- name: Checkout target branch
  tags:
    - rpc
    - git
  command: >
    git checkout {{targetBranch}}
    chdir={{rpc_repo_dir}}
  when: TRIGGER == "github"

- name: Merge PR
  tags:
    - rpc
    - git
  command: >
    git merge --no-edit origin/pr/{{pullRequestID}}
    chdir={{rpc_repo_dir}}
  when: TRIGGER == "github"
