---
- name: Stop nova-compute service
  command: service nova-compute stop
  ignore_errors: yes

- name: Gather VMs
  virt: command=list_vms
  register: instances
  ignore_errors: yes

- name: Destroy VMs
  virt: name={{ item }} command=destroy
  with_items: instances.list_vms
  ignore_errors: yes

- name: Uninstall nova and python-neutronclient
  pip: name={{ item }} state=absent
  with_items:
    - nova
    - python-neutronclient
  ignore_errors: yes

- name: Remove nova directories
  file: path={{ item }} state=absent
  with_items:
    - /opt/nova*
    - /etc/nova
    - /var/log/nova
    - /var/lib/nova
  ignore_errors: yes
