---
- name: Install xfsprogs
  apt:
    name: xfsprogs
    state: present
    update_cache: yes

- name: Create Swift logical volumes
  lvol:
    vg: "{{ swift_config.vg }}"
    lv: "{{ item.name }}"
    size: "{{ swift_config.lv_size }}"
    force: yes
  with_items: swift_config.drives

- name: Create and expand Swift's XFS filesystems
  filesystem:
    fstype: xfs
    dev: /dev/{{ swift_config.vg }}/{{ item.name }}
    #TODO(jpmontez): Add when Ansible 2.0 is released - resizefs: yes
  with_items: swift_config.drives

- name: Mount Swift partitions
  mount:
    name: "{{ swift_config.mount_point }}/{{ item.name }}"
    src: /dev/{{ swift_config.vg }}/{{ item.name }}
    opts: "{{ swift_config.mount_opts }}"
    state: mounted
    fstype: xfs
  with_items: swift_config.drives
