---
- name: Delete os-ansible-deployment repo
  command: rm -rf "{{ lookup('env', 'HOME') }}/os-ansible-deployment"
  ignore_errors: yes

- name: Clone os-ansible-deployment repo
  git: repo=https://github.com/stackforge/os-ansible-deployment dest="{{ lookup('env', 'HOME') }}/os-ansible-deployment"

- name: Checkout target branch
  command: git checkout {{targetBranch}}
  args: chdir="{{ lookup('env', 'HOME') }}/os-ansible-deployment"

- name: Install pip
  shell: "curl https://bootstrap.pypa.io/get-pip.py|python"

- name: Install pip requirements
  pip: requirements="{{ lookup('env', 'HOME') }}/os-ansible-deployment/requirements.txt"

- name: Get environment_md5 fact for user config
  stat: path="{{ lookup('env', 'HOME') }}/rpc_deploy/rpc_environment.yml"
  register: st

- name: Set environment version
  lineinfile: >
  	dest="{{ lookup('env', 'HOME') }}/rpc_deploy/rpc_user_config.yml"
  	regexp="^environment_version"
  	line="environment_version: {{st.stat.md5}}"

- name: Set virt_type to kvm
  lineinfile: >
    dest="{{ lookup('env', 'HOME') }}/rpc_deploy/user_variables.yml"
    regexp="^virt_type"
    line="virt_type: kvm"
