---
- name: install git
  apt:
    pkg: git
    state: latest

- name: Configure git identity
  tags:
    - rpc
    - git
  shell: >
    git config --global user.email "jenkins@propter.net";
    git config --global user.name "Jenkins"

- name: Delete RPC repo
  tags:
    - rpc
    - git
  command:
    rm -rf {{rpc_repo_dir}}

- name: Clone stackforge repo
  tags:
    - rpc
    - git
  git: >
    repo=https://github.com/stackforge/os-ansible-deployment
    dest={{rpc_repo_dir}}

- name: Fetch origin
  tags:
    - rpc
    - git
  command: >
    git fetch origin
    chdir={{rpc_repo_dir}}

- name: Checkout target branch
  tags:
    - rpc
    - git
  command: >
    git checkout {{targetBranch}}
    chdir={{rpc_repo_dir}}

- name: Get change from gerrit
  tags:
    - rpc
    - git
  shell:
    git fetch https://review.openstack.org/stackforge/os-ansible-deployment {{GERRIT_REFSPEC}}
  args:
    chdir: "{{rpc_repo_dir}}"

- name: Merge Review
  tags:
    - rpc
    - git
  command: >
    git merge FETCH_HEAD
    chdir={{rpc_repo_dir}}
