---
- name: Add VerifyHostKeyDNS to ssh options
  lineinfile:
    dest: ~/.ssh/config
    line: "{{ item }}"
    create: yes
  with_items:
    - "VerifyHostKeyDNS yes"
    - "StrictHostKeyChecking no"

- name: Install git
  apt:
    pkg: git
    state: latest

- name: Configure git identity
  shell: >
    git config --global user.email "jenkins@propter.net";
    git config --global user.name "Jenkins"

- name: Delete repo
  file: >
    path={{ product_repo_dir }}
    state=absent

- name: Clone repo
  git: >
    repo={{ product_url }}
    dest={{ product_repo_dir }}
    recursive=yes
    accept_hostkey=True

- name: Fetch origin
  command: git fetch origin chdir={{ product_repo_dir }}

- name: Checkout target branch
  command: git checkout {{ product_branch }} chdir={{ product_repo_dir }}

- name: Get change from gerrit
  shell:
    git fetch https://review.openstack.org/openstack/openstack-ansible {{ GERRIT_REFSPEC }}
  args:
    chdir: "{{ product_repo_dir }}"
  when: GERRIT_REFSPEC is defined

- name: Merge Review
  command: >
    git merge FETCH_HEAD
    chdir={{ product_repo_dir }}
  when: GERRIT_REFSPEC is defined
