---
- name: add verifyhostkeydns to ssh options
  lineinfile:
    dest: ~/.ssh/config
    line: "{{ item }}"
    create: yes
  with_items:
    - "VerifyHostKeyDNS yes"
    - "StrictHostKeyChecking no"

- name: install git
  apt:
    pkg: git
    state: latest

- name: Configure git identity
  tags:
    - rpc
    - osad
    - git
  shell: >
    git config --global user.email "jenkins@propter.net";
    git config --global user.name "Jenkins"

- name: Delete repo
  tags:
    - rpc
    - osad
    - git
  file: >
    path={{ rpc_repo_dir }}
    state=absent

- name: Clone repo
  tags:
    - rpc
    - osad
    - git
  git: >
    repo={{ repo_url }}
    dest={{ repo_dir }}
    accept_hostkey=True

- name: Fetch origin
  tags:
    - rpc
    - osad
    - git
  command: >
    git fetch origin
    chdir={{ repo_dir }}

- name: Checkout target branch
  tags:
    - rpc
    - osad
    - git
  command: >
    git checkout {{ repo_branch }}
    chdir={{ repo_dir }}

- name: Get change from gerrit
  tags:
    - osad
    - git
  shell:
    git fetch https://review.openstack.org/stackforge/os-ansible-deployment {{GERRIT_REFSPEC}}
  args:
    chdir: "{{ repo_dir }}"
  when: GERRIT_REFSPEC is defined

- name: Merge Review
  tags:
    - osad
    - git
  command: >
    git merge FETCH_HEAD
    chdir={{ repo_dir }}
  when: GERRIT_REFSPEC is defined
