---
- name: Update package cache
  apt: update_cache=yes

- name: Perform dist-upgrade
  apt: upgrade=dist

- name: install all required packages
  apt: pkg={{ item }} state=latest
  with_items: packages
