---
- name: Install pip requirements
  pip: requirements={{ oa_repo_dir }}/requirements.txt

- name: Create OA configuration directory
  file: 
    path: /etc/{{ config_prefix }}_deploy/
    state: directory
    mode: 0755

- name: Copy OA configuration files
  shell: cp --recursive {{ oa_repo_dir }}/etc/{{ config_prefix }}_deploy/* /etc/{{ config_prefix }}_deploy

- name: Gather environment MD5
  stat: path=/etc/{{ config_prefix }}_deploy/{{ config_prefix }}_environment.yml
  register: environment_version

- name: Install user configuration file
  template: src=user_config.j2
            dest=/etc/{{ config_prefix }}_deploy/{{ config_prefix }}_user_config.yml

- name: Generate passphrases
  command: "{{ oa_repo_dir }}/scripts/pw-token-gen.py --file /etc/{{ config_prefix }}_deploy/user_secrets.yml"

- name: Update user_variable glance_default_store
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "glance_default_store: swift"
    regexp: "^glance_default_store:.*"

- name: Update user_variable glance_notification_driver
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "glance_notification_driver: noop"
    regexp: "^glance_notification_driver:.*"

- name: Update user_variable glance_swift_store_auth_address
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "glance_swift_store_auth_address: '{{'{{'}} auth_identity_uri {{'}}'}}'"
    regexp: "^glance_swift_store_auth_address:.*"

- name: Update user_variable glance_swift_default_store_container
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "glance_swift_store_container: glance_images"
    regexp: "^glance_swift_store_container:.*"

- name: Update user_variable glance_swift_store_endpoint_type
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "glance_swift_store_endpoint_type: internalURL"
    regexp: "^glance_swift_store_endpoint_type:.*"

- name: Update user_variable glance_swift_store_key
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "glance_swift_store_key: '{{'{{'}} glance_service_password {{'}}'}}'"
    regexp: "^glance_swift_store_key:.*"

- name: Update user_variable glance_swift_store_region
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "glance_swift_store_region: RegionOne"
    regexp: "^glance_swift_store_region:.*"

- name: Update user_variable glance_swift_store_user
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "glance_swift_store_user: service:glance"
    regexp: "^glance_swift_store_user:.*"

- name: Add user_variable tempest_public_subnet_cidr
  lineinfile:
    dest: /etc/{{config_prefix}}_deploy/user_variables.yml
    line: "tempest_public_subnet_cidr: '172.29.248.0/22'"
