swift:
  service_names:
    - swift-account-server
    - swift-account-auditor
    - swift-account-replicator
    - swift-account-reaper
    - swift-account-server-replicator
    - swift-object-server
    - swift-object-auditor
    - swift-object-replicator
    - swift-object-updater
    - swift-object-server-replicator
    - swift-container-server
    - swift-container-auditor
    - swift-container-replicator
    - swift-container-sync
    - swift-container-updater
    - swift-container-server-replicator
    - swift-proxy-server
