---
- name: Ensure hosts exist
  tags: ensure
  local_action:
    module: rax
    name: "{{inventory_hostname}}"
    credentials: "{{rax_creds}}"
    keypair: "{{rax_keypair}}"
    networks: "{{rax_net_labels}}"
    region: "{{rax_region}}"
    flavor: "{{rax_flavor}}"
    image: "{{rax_image}}"
    disk_config: "{{rax_diskconfig}}"
    wait: yes
    wait_timeout: 600
    state: present
  register: rax

- name: Store host access IPs
  tags: ensure
  set_fact: ansible_ssh_host={{item.accessIPv4}} networks={{item.rax_networks}}
  when: item.name == inventory_hostname # Avoid dupes
  with_items: rax.instances

- name: Wait for ssh to be available
  tags: ensure
  local_action:
    module: wait_for
    host: "{{item.accessIPv4}}"
    port: 22
    state: started
    timeout: 300
    search_regex: OpenSSH
  with_items: rax.instances
