---
- name: create rpc deploy conf.d folder
  file: path="{{ lookup('env', 'HOME') }}/rpc_deploy/conf.d" 
        state=directory 
        owner="{{ lookup('env', 'USER') }}
        mode=0755

- name: create and configure the swift.yml file
  template: src=swift.j2
            dest="{{ lookup('env', 'HOME') }}/rpc_deploy/conf.d/swift.yml"
            owner="{{ lookup('env', 'USER') }}
            mode=0644
