---
- name: Catalog containers
  command: lxc-ls
  register: containers
  ignore_errors: yes

- name: Stop containers
  lxc_container:
    name: "{{ item }}"
    state: stopped
  with_items: containers.stdout_lines
  when: containers.stdout_lines is defined

- name: Destroy containers
  lxc_container:
    name: "{{ item }}"
    state: absent
  with_items: containers.stdout_lines
  when: containers.stdout_lines is defined

- name: Remove all containers from /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "container"
    state: absent

- name: Recursive delete of /openstack directory
  shell: rm -rf /openstack/*
