---
- name: Delete os-ansible-deployment repo
  command: rm -rf "{{ lookup('env', 'HOME') }}/os-ansible-deployment"

- name: Clone os-ansible-deployment repo
  git: repo=https://github.com/stackforge/os-ansible-deployment 
       dest="{{ lookup('env', 'HOME') }}/os-ansible-deployment"
       version={{ targetBranch | default(master) }}

- name: change owner of os-ansible-deployment to current user
  file: path="{{ lookup('env', 'HOME') }}/os-ansible-deployment"
        state=directory
        recurse=yes
        owner="{{ lookup('env', 'USER') }}" 
        mode=0755

- name: Install pip
  shell: "curl https://bootstrap.pypa.io/get-pip.py|python"

- name: Install pip requirements
  pip: requirements="{{ lookup('env', 'HOME') }}/os-ansible-deployment/requirements.txt"

- name: create rpc deploy folder
  file: path="{{ lookup('env', 'HOME') }}/rpc_deploy" 
        state=directory 
        owner="{{ lookup('env', 'USER') }}" 
        mode=0755

- name: install rpc environment file
  copy: src="{{ lookup('env', 'HOME') }}/os-ansible-deployment/etc/rpc_deploy/rpc_environment.yml"
        dest="{{ lookup('env', 'HOME') }}/rpc_deploy/rpc_environment.yml"
        owner="{{ lookup('env', 'USER') }}" 
        mode=0644

- name: get environment version md5sum
  stat: path="{{ lookup('env', 'HOME') }}/rpc_deploy/rpc_environment.yml"
  register: environment_version

- name: install rpc user config file
  template: src=rpc_user_config.j2 
            dest="{{ lookup('env', 'HOME') }}/rpc_deploy/rpc_user_config.yml"
            owner="{{ lookup('env', 'USER') }}" 
            mode=0644

- name: set rpc_deploy user_variables file
  shell: python pw-token-gen.py --file ../etc/rpc_deploy/user_variables.yml
         chdir="{{ lookup('env', 'HOME') }}/os-ansible-deployment/scripts"

- name: change owner of user_variables file
  file: path="{{ lookup('env', 'HOME') }}/os-ansible-deployment/etc/rpc_deploy/user_variables.yml"
        owner="{{ lookup('env', 'USER') }}" 
        mode=0644

- name: copy user_variables file to rpc_deploy directory
  copy: src="{{ lookup('env', 'HOME') }}/os-ansible-deployment/etc/rpc_deploy/user_variables.yml"
        dest="{{ lookup('env', 'HOME') }}/rpc_deploy/user_variables.yml"
        owner="{{ lookup('env', 'USER') }}" 
        mode=0644
