---
- name: Stop neutron-linuxbridge-agent
  command: service neutron-linuxbridge-agent stop
  ignore_errors: yes

- name: Uninstall neutron and python-novaclient
  pip: name={{ item }} state=absent
  with_items:
    - neutron
    - python-novaclient

- name: Remove neutron directories
  file: path={{ item }} state=absent
  with_items:
    - /opt/neutron*
    - /etc/neutron
    - /var/log/neutron
    - /var/lib/neutron
