---
- name: Authorize SSH keys
  tags: keys
  authorized_key: >
    key={{lookup('file', item|basename)}}
    user=root
    state=present
  with_fileglob: id_*.pub

- name: Copy SSH keys
  tags: keys
  copy: >
    src={{lookup('file', item|basename}}
    dest=~/.ssh/{{lookup('file', item|basename)}}
  with_fileglob: id_*

- name: Updating packages
  tags: packages
  apt: update_cache=yes upgrade=dist

- name: Install packages
  tags: packages
  apt: pkg=bridge-utils,git state=present

- name: Configure vxlan tunnel
  interfaces: >-
    name={{iface.tunnel_name}}
    iface_type=manual
    updown="pre-up ip link add $IFACE type vxlan id {{iface.tunnel_id}} group 239.0.0.{{iface.tunnel_id}} dev {{iface.tunnel_dev}} || true","up ip link set $IFACE up","down ip link set $IFACE down","post-down ip link del $IFACE || true"

- name: Configure br-mgmt bridge
  interfaces: >-
    name=br-mgmt
    iface_type=static
    address={{iface.tunnel_ip}}
    updown="bridge_ports {{iface.tunnel_name}}"
