---
- name: Authorize SSH keys
  tags: keys
  authorized_key: key="{{lookup('file', item|basename)}}" user=root state=present
  with_fileglob: id_*.pub

- name: Updating packages
  tags: packages
  apt: update_cache=yes upgrade=dist

# - name: Clear existing cluster hosts
#   tags: hosts
#   host: hostname={{inventory_hostname}} state=absent
#   register: result
#   until: not result.changed
#   retries: 10
#   delay: 0
#
# - name: Add cluster hosts svc nets
#   tags: hosts
#   host: hostname={{item}} ip={{hostvars[item].ifaces.mgmt.ipv4}} state=present
#   when: "'mgmt' in hostvars[item].ifaces"
#   with_items: groups.hosts
#
# - name: Add docker registry to hosts
#   tags: hosts
#   host: hostname=registry.docker ip=10.208.163.157 state=present

- name: Configure cloud network interfaces
  tags: networks
  interfaces: name={{item.iface}} state=present addr_family=inet iface_type=static address={{item.ipv4}} netmask={{item.mask}}
  when: item.iface in ansible_interfaces
  with_items: ifaces
  notify:
  - Down interfaces
  - Flush interfaces
  - Up interfaces
  - Ping addresses
