---
- name: Update package cache
  apt: update_cache=yes

- name: Perform dist-upgrade
  apt: upgrade=dist

- name: Install lldpd
  apt: pkg=lldpd state=latest

- name: Install vlan
  apt: pkg=vlan state=latest

- name: Install bridge-utils
  apt: pkg=bridge-utils state=latest

- name: Install pip
  tags: rpc
  shell: "curl https://bootstrap.pypa.io/get-pip.py|python"
