---

# Generic task w/ all lab prefixes to skip missing tags
# https://github.com/ansible/ansible/pull/9418
- hosts: all
  user: root
  gather_facts: no
  tags:
    - nightly
    - commit
    - release
    - openstack-ansible
  tasks:
    - name: Ping hosts
      ping:

## --------- [ Prepare Cluster ] ---------------
- hosts: all
  user: root
  gather_facts: no
  tags:
    - prepare
    - packages
  roles:
    - packages

- hosts: all
  user: root
  gather_facts: no
  tags:
    - pip
  roles:
    - pip

- hosts: all
  user: root
  gather_facts: yes
  tags:
    - prepare
    - networking
  roles:
    - networking

- hosts: cinder
  user: root
  gather_facts: yes
  tags:
    - nightly
    - commit
    - cinder-volume
  roles:
    - volumes

- hosts: swift
  user: root
  gather_facts: yes
  tags:
    - nightly
    - commit
    - configure-swift-lvs
  roles:
    - configure-swift-lvs

- hosts: swift
  user: root
  gather_facts: yes
  tags:
    - configure-swift-disks
  roles:
    - configure-swift-disks

- hosts: infrastructure[0]
  user: root
  gather_facts: no
  tags:
    - prepare
    - git
  roles:
    - setup-git

- hosts: infrastructure[0]
  user: root
  gather_facts: no
  tags:
    - prepare
    - bootstrap-ansible
  roles:
    - role: run-script-from-openstack-ansible
      script_name: bootstrap-ansible

- hosts: infrastructure[0]
  user: root
  gather_facts: no
  tags:
    - prepare
    - configure-osa
  roles:
    - configure-compute
    - configure-swift

- hosts: infrastructure[0]
  user: root
  gather_facts: no
  tags:
    - rpc-openstack
  roles:
    - configure-rpc

- hosts: infrastructure[0]
  user: root
  gather_facts: no
  tags:
    - rpc-ceph
  roles:
    - configure-ceph

- hosts: all
  user: root
  gather_facts: no
  tags:
    - reboot
  roles:
    - reboot

## ---------- [ Upgrade ] ------------
- hosts: infrastructure[0]
  user: root
  gather_facts: no
  tags:
    - upgrade
  roles:
    - setup-git

## --------- [ Cleanup Cluster ] ------------------
- hosts: all
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - teardown-containers

- hosts: compute
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - teardown-compute-node

- hosts: swift
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - teardown-swift-node

- hosts: all
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - teardown-pip

- hosts: all
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - cleanup-host

## --------- [ Rekick Cluster ] ------------------
- hosts: cinder
  gather_facts: no
  user: root
  tags:
    - cleanup
    - rekick
  roles:
    - cleanup-cinder-volumes

- hosts: all
  gather_facts: no
  user: root
  tags:
    - rekick
  roles:
    - razor-rekick
