---

## --------- [ Prepare Cluster ] ---------------

- hosts: all
  user: root
  tags: prepare
  vars_files:
    - vars/packages.yml
  roles:
    - packages

- hosts: all
  user: root
  tags: prepare
  vars_files:
    - vars/pip.yml
  roles:
    - pip

- hosts: all
  user: root
  tags: prepare
  roles:
    - networking

- hosts: infrastructure[0]
  user: root
  tags: prepare
  roles:

    - setup-git

    - role: run-script-from-os-ansible-deployment
      script_name: bootstrap-ansible

    - configure-rpc-compute

- hosts: all
  user: root
  tags: prepare
  roles:
    - reboot

## --------- [ Run os-ansible-deployment ] ---------------
- hosts: infrastructure[0]
  tags: run
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-playbooks
      script_env:
        DEPLOY_TEMPEST: "yes"

## --------- [ Test with tempest ] ---------------
- hosts: infrastructure[0]
  tags: test
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-tempest
