---
## --------- [ Prepare Cluster ] ---------------

- hosts: all
  user: root
  tags: prepare
  vars_files:
    - vars/packages.yml
  roles:
    - packages

- hosts: all
  user: root
  tags: prepare
  vars_files:
    - vars/pip.yml
  roles:
    - pip

- hosts: all
  user: root
  tags: prepare
  roles:
    - networking
    - volumes

- hosts: swift
  user: root
  tags: prepare
  roles:
    - configure-swift-lvs

- hosts: infrastructure[0]
  user: root
  tags: prepare
  roles:
    - setup-git

- hosts: infrastructure[0]
  tags: prepare
  user: root
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: bootstrap-ansible

- hosts: infrastructure[0]
  user: root
  tags:
    - configure
    - prepare
  roles:
    - configure-compute
    - configure-swift

- hosts: all
  user: root
  tags:
    - reboot
    - prepare
  roles:
    - reboot

## ---------- [ Upgrade ] ------------
- hosts: infrastructure[0]
  tags: upgrade
  roles:
    - role: setup-git

## --------- [ Cleanup Cluster ] ------------------
- include: teardown.yml
  tags: rekick

## --------- [ Rekick Cluster ] ------------------
- hosts: cinder
  gather_facts: no
  user: root
  tags:
    - cleanup
    - rekick
  roles:
    - cleanup-cinder-volumes

- hosts: all
  gather_facts: no
  user: root
  tags: rekick
  roles:
    - razor-rekick
