---

## --------- [ Prepare Cluster ] ---------------

- hosts: all
  user: root
  tags: prepare
  vars_files:
    - vars/packages.yml
  roles:
    - packages

- hosts: all
  user: root
  tags: prepare
  vars_files:
    - vars/pip.yml
  roles:
    - pip

- hosts: all
  user: root
  tags: prepare
  roles:
    - networking

- hosts: infrastructure[0]
  user: root
  tags: prepare
  roles:
    - setup-git

- hosts: infrastructure[0]
  user: root
  tags: configure
  roles:
    - configure-rpc-compute
    - configure-rpc-swift

- hosts: all
  user: root
  tags: reboot
  roles:
    - reboot

## --------- [ Run os-ansible-deployment ] ----------
- hosts: infrastructure[0]
  tags: run
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-playbooks
      script_env:
        DEPLOY_TEMPEST: "yes"

## --------- [ Test with tempest ] ---------------
- hosts: infrastructure[0]
  tags: test
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-tempest

## ---------- [ Upgrade ] ------------
- hosts: infrastructure[0]
  tags: upgrade
  roles:
    - role: setup-git

## --------- [ Cleanup Cluster ] ------------------
- hosts: infrastructure
  user: root
  gather_facts: no
  tags: cleanup
  roles:
    - teardown-infrastructure-node

- hosts: network
  user: root
  gather_facts: no
  tags: cleanup
  roles:
    - teardown-network-node

- hosts: cinder
  user: root
  gather_facts: no
  tags: cleanup
  roles:
    - cleanup-cinder-volumes
    - teardown-cinder-node

- hosts: swift
  user: root
  gather_facts: no
  tags: cleanup
  roles:
    - teardown-swift-node

- hosts: logger
  user: root
  gather_facts: no
  tags: cleanup
  roles:
    - teardown-logging-node

- hosts: compute
  user: root
  gather_facts: no
  tags: cleanup
  roles:
    - teardown-compute-node

- hosts: all
  user: root
  gather_facts: no
  tags: cleanup
  roles:
    - cleanup-host
