---

## --------- [ Prepare Cluster ] ---------------
- hosts: all
  user: root
  tags: prepare
  vars_files:
    - vars/packages.yml
  roles:
    - packages

- hosts: all
  user: root
  tags: prepare
  vars_files:
    - vars/pip.yml
  roles:
    - pip

- hosts: all
  user: root
  tags: prepare
  roles:
    - networking

- hosts: infrastructure[0]
  user: root
  tags: prepare
  roles:
    - setup-git


- hosts: infrastructure[0]
  tags: prepare
  user: root
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: bootstrap-ansible

- hosts: infrastructure[0]
  user: root
  tags:
    - configure
    - prepare
  roles:
    - configure-compute
    - configure-swift

- hosts: all
  user: root
  tags:
    - prepare
  roles:
    - reboot

## ---------- [ Upgrade ] ------------
- hosts: infrastructure[0]
  tags: upgrade
  roles:
    - role: setup-git

## --------- [ Cleanup Cluster ] ------------------
- include: teardown.yml
  tags: cleanup

- hosts: all
  user: root
  tags:
    - cleanup
  roles:
    - reboot


