---

## --------- [ Prepare Cluster ] ---------------
- include: packages.yml tags=prepare

- include: pip.yml tags=prepare

- include: networking.yml tags=prepare

- hosts: infrastructure[0]
  user: root
  tags: prepare
  roles:
    - setup-git
    - role: run-script-from-os-ansible-deployment
      script_name: bootstrap-ansible

- hosts: infrastructure[0]
  user: root
  tags: configure
  roles:
    - configure-rpc-compute
    - configure-rpc-swift

- include: reboot-hosts.yml tags=reboot

## --------- [ Run os-ansible-deployment ] ----------
- hosts: infrastructure[0]
  tags: run
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-playbooks
      script_env:
        DEPLOY_LB: "no"
        DEPLOY_TEMPEST: "yes"
        DEPLOY_RPC_SUPPORT: "no"

## --------- [ Test with tempest ] ---------------
- hosts: infrastructure[0]
  tags: test
  roles:
    - role: run-script-from-os-ansible-deployment
      script_name: run-tempest

## ---------- [ Upgrade ] ------------
- hosts: infrastructure[0]
  tags: upgrade
  roles:
    - role: setup-git

## --------- [ Cleanup Cluster ] ------------------
- include: teardown.yml tags=cleanup
