---
- hosts: all
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - teardown-containers

- hosts: compute
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - teardown-compute-node

- hosts: swift
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - teardown-swift-node

- hosts: all
  user: root
  tags:
    - cleanup
    - rekick
  gather_facts: no
  roles:
    - cleanup-host
