---
# Cider used in the Management network
mgmt_cidr: 172.20.{{cluster_id}}.0/24

# Cidr used in the VM network
vmnet_cidr: 172.24.0.0/24

# overrides anything else any where.
global_overrides:
  internal_lb_vip_address: 172.20.{{cluster_id}}.1
  external_lb_vip_address: {{hostvars[groups.hosts[0]]["ansible_ssh_host"]}}

# User defined Infrastructure Hosts, this should be a required group
infra_hosts:
{% for host in groups.hosts %}
  {{host}}:
    ip: {{hostvars[host]["ansible_ssh_host"]}}
{% endfor %}

# User defined Compute Hosts, this should be a required group
compute_hosts:
  {{groups.hosts[3 % host_count|int]}}:
    ip: {{hostvars[groups.hosts[3 % host_count|int]]["ansible_ssh_host"]}}

# User defined Storage Hosts, this should be a required group
storage_hosts:
  {{groups.hosts[4 % host_count|int]}}:
    ip: {{hostvars[groups.hosts[4 % host_count|int]]["ansible_ssh_host"]}}
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          driver: cinder.volume.drivers.lvm.LVMISCSIDriver
          backend: LVM_iSCSI

# User defined Logging Hosts, this should be a required group
log_hosts:
  {{groups.hosts[5 % host_count|int]}}:
    ip: {{hostvars[groups.hosts[5 % host_count|int]]["ansible_ssh_host"]}}

# User defined Networking Hosts, this should be a required group
network_hosts:
  {{groups.hosts[6 % host_count|int]}}:
    ip: {{hostvars[groups.hosts[6 % host_count|int]]["ansible_ssh_host"]}}
