---
# Cider used in the Management network
mgmt_cidr: {{rax_net_info[0].cidr}}

# Cidr used in the VM network
vmnet_cidr: 172.16.32.0/24

# overrides anything else any where.
global_overrides:
  glance_default_store: file
  internal_lb_vip_address: 172.16.0.1
  external_lb_vip_address: {{hostvars[groups.hosts[0]]["ansible_ssh_host"]}}

# User defined Infrastructure Hosts, this should be a required group
infra_hosts:
{% for host in groups.hosts %}
  {{host}}:
    ip: {{hostvars[host]["ansible_ssh_host"]}}
{% endfor %}

# User defined Compute Hosts, this should be a required group
compute_hosts:
  {{groups.hosts[3]}}:
    ip: {{hostvars[groups.hosts[3]]["ansible_ssh_host"]}}

# User defined Storage Hosts, this should be a required group
storage_hosts:
  {{groups.hosts[4]}}:
    ip: {{hostvars[groups.hosts[4]]["ansible_ssh_host"]}}
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          driver: cinder.volume.drivers.lvm.LVMISCSIDriver
          backend: LVM_iSCSI

# User defined Logging Hosts, this should be a required group
log_hosts:
  {{groups.hosts[0]}}:
    ip: {{hostvars[groups.hosts[0]]["ansible_ssh_host"]}}

# User defined Networking Hosts, this should be a required group
network_hosts:
  {{groups.hosts[0]}}:
    ip: {{hostvars[groups.hosts[0]]["ansible_ssh_host"]}}
