---
mgmt_cidr: 172.20.{{cluster_id}}.0/24
vmnet_cidr: 172.24.0.0/24

global_overrides:
  internal_lb_vip_address: 172.20.{{cluster_id}}.1
  external_lb_vip_address: {{hostvars[groups.hosts[0]]["ansible_ssh_host"]}}
  tunnel_bridge: br-vmnet
  container_bridge: br-mgmt
  lb_name: lb_name_in_core
  neutron_provider_networks:
    - network:
        container_bridge: "br-vmnet"
        container_interface: "eth2"
        type: "vxlan"
        range: "1:1000"
        net_name: "vmnet"
    - network:
        container_bridge: "br-ext"
        container_interface: "eth3"
        type: "flat"
        net_name: "extnet"
    - network:
        container_bridge: "br-ext"
        container_interface: "eth3"
        type: "vlan"
        range: "1:1"
        net_name: "extnet"

infra_hosts:
{% if host_count|int >= 3 %}
{% set count = 3 %}
{% else %}
{% set count = host_count|int %}
{% endif -%}
{% for index in range(count) %}
  {{groups.hosts[index]}}:
    ip: {{hostvars[groups.hosts[index]]["ansible_ssh_host"]}}
{% endfor %}

compute_hosts:
  {{groups.hosts[3 % host_count|int]}}:
    ip: {{hostvars[groups.hosts[3 % host_count|int]]["ansible_ssh_host"]}}

storage_hosts:
  {{groups.hosts[4 % host_count|int]}}:
    ip: {{hostvars[groups.hosts[4 % host_count|int]]["ansible_ssh_host"]}}
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          driver: cinder.volume.drivers.lvm.LVMISCSIDriver
          backend: LVM_iSCSI

log_hosts:
  {{groups.hosts[5 % host_count|int]}}:
    ip: {{hostvars[groups.hosts[5 % host_count|int]]["ansible_ssh_host"]}}

network_hosts:
  {{groups.hosts[6 % host_count|int]}}:
    ip: {{hostvars[groups.hosts[6 % host_count|int]]["ansible_ssh_host"]}}

haproxy_hosts:
  {{groups.hosts[0]}}:
    ip: {{hostvars[groups.hosts[0]]["ansible_ssh_host"]}}
